# Generated by Django 5.2.7 on 2025-11-16 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('core', '0001_initial'),
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='categorias.categoria')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.estado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tallas', to='core.estado')),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
                'db_table': 'talla',
            },
        ),
        migrations.CreateModel(
            name='TiendaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tienda_productos', to='core.estado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes_tienda', to='productos.producto')),
                ('talla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_tienda', to='productos.talla')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Producto de Tienda',
                'verbose_name_plural': 'Productos de Tienda',
                'db_table': 'tienda_producto',
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.URLField(max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagenes_producto', to='core.estado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.tiendaproducto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
                'db_table': 'imagen_producto',
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='producto_nombre_38c699_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='producto_categor_b30d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='tiendaproducto',
            index=models.Index(fields=['tienda', 'producto'], name='tienda_prod_tienda__4f5d53_idx'),
        ),
        migrations.AddIndex(
            model_name='tiendaproducto',
            index=models.Index(fields=['producto'], name='tienda_prod_product_7fc004_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tiendaproducto',
            unique_together={('tienda', 'producto', 'talla')},
        ),
        migrations.AddIndex(
            model_name='imagenproducto',
            index=models.Index(fields=['producto'], name='imagen_prod_product_d1ac3d_idx'),
        ),
    ]
