# Generated by Django 5.2.7 on 2025-11-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='archivo',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
