# Generated by Django 5.2.7 on 2025-10-23 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendaproducto',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tiendas.tienda'),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.tiendaproducto'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='producto_nombre_38c699_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='producto_categor_b30d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='tiendaproducto',
            index=models.Index(fields=['tienda', 'producto'], name='tienda_prod_tienda__4f5d53_idx'),
        ),
        migrations.AddIndex(
            model_name='tiendaproducto',
            index=models.Index(fields=['producto'], name='tienda_prod_product_7fc004_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tiendaproducto',
            unique_together={('tienda', 'producto', 'talla')},
        ),
        migrations.AddIndex(
            model_name='imagenproducto',
            index=models.Index(fields=['producto'], name='imagen_prod_product_d1ac3d_idx'),
        ),
    ]
