# Generated by Django 5.2.7 on 2025-11-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_imagenproducto_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='archivo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
