# Generated by Django 5.2.7 on 2025-10-23 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('foto_perfil', models.URLField(blank=True, max_length=500, null=True)),
                ('codigo_qr', models.URLField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiendas', to='core.estado')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
                'db_table': 'tienda',
                'indexes': [models.Index(fields=['propietario'], name='tienda_propiet_ff60f4_idx'), models.Index(fields=['nombre'], name='tienda_nombre_2ccd75_idx')],
            },
        ),
    ]
