# Generated by Django 5.2.7 on 2025-11-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0002_alter_tienda_codigo_qr_alter_tienda_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='codigo_qr',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='foto_perfil',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
