# Generated by Django 5.2.7 on 2025-11-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auditoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoria',
            options={'ordering': ['-fecha'], 'verbose_name': 'Auditoría', 'verbose_name_plural': 'Auditorías'},
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='usuario',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='usuario_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='usuario_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='usuario_tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['usuario_tipo', 'usuario_id'], name='auditoria_usuario_f1deb7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['fecha'], name='auditoria_fecha_b71d64_idx'),
        ),
        migrations.AlterModelTable(
            name='auditoria',
            table='auditoria',
        ),
    ]
