# Generated by Django 5.2.7 on 2025-11-20 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_auditoria_options_remove_auditoria_usuario_and_more'),
        ('ventas', '0002_venta_comprobante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta_pendiente', 'Venta Pendiente'), ('venta_confirmada', 'Venta Confirmada'), ('venta_rechazada', 'Venta Rechazada'), ('nuevo_producto', 'Nuevo Producto')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuarios.usuario')),
                ('venta_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
            options={
                'db_table': 'notificacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
