# Generated by Django 5.2.7 on 2025-11-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('usuario_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('es_vendedor', models.BooleanField(default=False)),
                ('accion', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría de Usuario',
                'verbose_name_plural': 'Auditorías de Usuarios',
                'db_table': 'auditoria_usuario',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario_id'], name='auditoria_u_usuario_1dd093_idx'), models.Index(fields=['fecha'], name='auditoria_u_fecha_19ebbf_idx')],
            },
        ),
    ]
