# Generated by Django 5.2.7 on 2025-10-23 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favoritos', '0001_initial'),
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritos',
            name='tienda_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='productos.tiendaproducto'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='usuarios.usuario'),
        ),
        migrations.AddIndex(
            model_name='favoritos',
            index=models.Index(fields=['usuario'], name='favoritos_usuario_ed02b8_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritos',
            index=models.Index(fields=['tienda_producto'], name='favoritos_tienda__3c7754_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritos',
            unique_together={('usuario', 'tienda_producto')},
        ),
    ]
