# Generated by Django 5.2.7 on 2025-11-16 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('productos', '0001_initial'),
        ('tiendas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.estado')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='tiendas.tienda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venta_productos', to='core.estado')),
                ('tienda_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='productos.tiendaproducto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'venta_producto',
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['usuario'], name='venta_usuario_2a4993_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['tienda'], name='venta_tienda__3d317e_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha_creacion'], name='venta_fecha_c_468312_idx'),
        ),
        migrations.AddIndex(
            model_name='ventaproducto',
            index=models.Index(fields=['venta'], name='venta_produ_venta_i_a895f5_idx'),
        ),
        migrations.AddIndex(
            model_name='ventaproducto',
            index=models.Index(fields=['tienda_producto'], name='venta_produ_tienda__43e438_idx'),
        ),
    ]
