# Generated by Django 5.2.7 on 2025-11-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='comprobante',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
